// CLICK SCIENCE 목록 — 새 시뮬은 여기에 한 줄만 추가하면 된다.
// subject: phys 물리 · chem 화학 · life 생명 · earth 지구
// tags: sim 시뮬 · game 게임형 · 3d 3D · mic 마이크 · cam 카메라 · sensor 센서 · data 데이터
// thumb 가 없으면 thumbs/<id>.jpg 를 쓴다. shot 은 썸네일을 찍을 주소(없으면 url).
const B = 'https://scienceisjo.github.io/';
const LW = B + 'lightandwave/';
const EL = B + 'electricity/';
const GA = B + 'gas-properties/';
const ST = B + 'starandspace/';
const SO = B + 'solar-system/';
const PM = B + 'propertiesofmatter/';
const SE = B + 'separationofmixture/';

const SIMS = [
  // ───────── 교육과정 핵심 개념 실험실 · 두 모드
  {"id":"cell-organization","own":true,"version":1,"missions":3,"subject":"life","unit":"생물의 구성과 다양성","grade":"중학교","tags":["sim"],"title":"세포의 구조는 하는 일과 어떻게 연결될까?","desc":"세포의 구조와 기능을 연결하고 세포에서 개체까지의 구성 단계를 비교한다.","url":"labs/cell-organization/"},
  {"id":"biodiversity-sort","own":true,"version":1,"missions":3,"subject":"life","unit":"생물의 구성과 다양성","grade":"중학교","tags":["sim"],"title":"닮았다는 이유만으로 같은 무리일까?","desc":"생물은 세포와 영양 방식 등의 근거로 분류하며 같은 종 안에도 변이가 있다.","url":"labs/biodiversity-sort/"},
  {"id":"heat-equilibrium","own":true,"version":1,"missions":7,"subject":"phys","unit":"열","grade":"중학교","tags":["sim","data"],"title":"열평형 입자 실험실","desc":"온도가 다른 두 물체가 열평형에 도달하는 과정을 탐색합니다.","url":"labs/heat-equilibrium/"},
  {"id":"conduction-camera","own":true,"version":1,"missions":6,"subject":"phys","unit":"열","grade":"중학교","tags":["sim","data"],"title":"가상 열화상 카메라","desc":"가상 열화상 카메라의 조건을 바꾸고 결과를 비교합니다.","url":"labs/conduction-camera/"},
  {"id":"heat-three-ways","own":true,"version":1,"missions":6,"subject":"phys","unit":"열","grade":"중학교","tags":["sim","data"],"title":"전도·대류·복사","desc":"전도·대류·복사의 조건을 바꾸고 결과를 비교합니다.","url":"labs/heat-three-ways/"},
  {"id":"specific-heat","own":true,"version":1,"missions":6,"subject":"phys","unit":"열","grade":"중학교","tags":["sim","data"],"title":"비열","desc":"비열의 조건을 바꾸고 결과를 비교합니다.","url":"labs/specific-heat/"},
  {"id":"thermal-expansion","own":true,"version":1,"missions":6,"subject":"phys","unit":"열","grade":"중학교","tags":["sim","data"],"title":"액체와 고체의 열팽창","desc":"액체와 고체의 열팽창의 조건을 바꾸고 결과를 비교합니다.","url":"labs/thermal-expansion/"},
  {"id":"bimetal-switch","own":true,"version":1,"missions":6,"subject":"phys","unit":"열","grade":"중학교","tags":["sim","data"],"title":"바이메탈 스위치","desc":"바이메탈 스위치의 조건을 바꾸고 결과를 비교합니다.","url":"labs/bimetal-switch/"},
  {"id":"sea-land-breeze","own":true,"version":1,"missions":6,"subject":"phys","unit":"열","grade":"중학교","tags":["sim","data"],"title":"해풍과 육풍","desc":"해풍과 육풍의 조건을 바꾸고 결과를 비교합니다.","url":"labs/sea-land-breeze/"},
  {"id":"cookware-test-bench","own":true,"version":1,"missions":6,"subject":"phys","unit":"열","grade":"중학교","tags":["sim","data"],"title":"조리 도구 재료 비교","desc":"조리 도구 재료 비교의 조건을 바꾸고 결과를 비교합니다.","url":"labs/cookware-test-bench/"},
  {"id":"particle-motion","own":true,"version":1,"missions":6,"subject":"chem","unit":"물질의 상태 변화","grade":"중학교","tags":["sim","data"],"title":"확산과 증발 입자 관찰실","desc":"확산과 증발 입자 관찰실의 조건을 바꾸고 결과를 비교합니다.","url":"labs/particle-motion/"},
  {"id":"state-change-particles","own":true,"version":1,"missions":7,"subject":"chem","unit":"물질의 상태 변화","grade":"중학교","tags":["sim","data"],"title":"세 상태와 상태 변화","desc":"세 상태와 상태 변화의 조건을 바꾸고 결과를 비교합니다.","url":"labs/state-change-particles/"},
  {"id":"phase-heat-curves","own":true,"version":1,"missions":8,"subject":"chem","unit":"물질의 상태 변화","grade":"중학교","tags":["sim","data"],"title":"상태 변화와 열에너지","desc":"상태 변화와 열에너지의 조건을 바꾸고 결과를 비교합니다.","url":"labs/phase-heat-curves/"},
  {"id":"force-balance","own":true,"version":3,"missions":7,"subject":"phys","unit":"힘의 작용","grade":"중학교","tags":["sim","data"],"title":"힘의 표현과 평형","desc":"힘의 크기와 방향을 더하고 평형 조건을 찾습니다.","url":"labs/force-balance/"},
  {"id":"gravity","own":true,"version":1,"missions":6,"subject":"phys","unit":"힘의 작용","grade":"중학교","tags":["sim","data"],"title":"중력 — 질량과 무게","desc":"중력 — 질량과 무게의 조건을 바꾸고 결과를 비교합니다.","url":"labs/gravity/"},
  {"id":"elasticity","own":true,"version":1,"missions":6,"subject":"phys","unit":"힘의 작용","grade":"중학교","tags":["sim","data"],"title":"탄성력","desc":"탄성력의 조건을 바꾸고 결과를 비교합니다.","url":"labs/elasticity/"},
  {"id":"friction","own":true,"version":3,"missions":7,"subject":"phys","unit":"힘의 작용","grade":"중학교","tags":["sim","data"],"title":"마찰력","desc":"마찰력의 조건을 바꾸고 결과를 비교합니다.","url":"labs/friction/"},
  {"id":"buoyancy","own":true,"version":1,"missions":6,"subject":"phys","unit":"힘의 작용","grade":"중학교","tags":["sim","data"],"title":"부력","desc":"부력의 조건을 바꾸고 결과를 비교합니다.","url":"labs/buoyancy/"},
  {"id":"motion","own":true,"version":1,"missions":7,"subject":"phys","unit":"힘의 작용","grade":"중학교","tags":["sim","data"],"title":"알짜힘과 운동 상태 변화","desc":"알짜힘에 따른 속력과 운동 방향 변화를 구별합니다.","url":"labs/motion/"},
  {"id":"syringe-particles","own":true,"version":3,"missions":6,"subject":"chem","unit":"기체의 성질","grade":"중학교","tags":["sim","data"],"title":"입자로 보는 기체의 성질","desc":"입자 운동과 충돌로 압력·부피·온도의 관계를 연결합니다.","url":"labs/syringe-particles/"},
  {"id":"planet-scale","own":true,"version":1,"missions":4,"subject":"earth","unit":"태양계","grade":"중학교","tags":["sim","data"],"title":"행성의 크기와 거리를 따로 비교하면?","desc":"행성의 크기와 거리는 다른 척도이며 지구형과 목성형의 특징을 근거로 분류한다.","url":"labs/planet-scale/"},
  {"id":"solar-activity","own":true,"version":1,"missions":3,"subject":"earth","unit":"태양계","grade":"중학교","tags":["sim"],"title":"흑점이 많으면 지구에는 꼭 문제가 생길까?","desc":"흑점은 태양 활동의 지표이며 지구 영향은 분출 방향과 여러 조건에 따라 달라진다.","url":"labs/solar-activity/"},
  {"id":"earth-sky","own":true,"version":1,"missions":4,"subject":"earth","unit":"태양계","grade":"중학교","tags":["sim","data"],"title":"지구가 움직이면 하늘은 어떻게 보일까?","desc":"지구 자전의 반대 방향으로 하늘이 겉보기 운동하며 공전하면 한밤중에 보는 먼 배경 방향이 달라진다.","url":"labs/earth-sky/"},
  {"id":"moon-geometry","own":true,"version":1,"missions":4,"subject":"earth","unit":"태양계","grade":"중학교","tags":["sim","data"],"title":"달의 모양과 식은 왜 다르게 변할까?","desc":"달의 위상은 밝은 반구를 보는 방향으로, 식은 실제 가림과 그림자로 설명한다.","url":"labs/moon-geometry/"},
  {"id":"solar-objects","own":true,"version":1,"missions":3,"subject":"earth","unit":"태양계","grade":"중학교","tags":["sim"],"title":"태양계의 천체는 어떻게 구별할까?","desc":"스스로 빛을 내는지, 무엇을 중심으로 도는지, 궤도 주변에서 어떤 역할인지로 태양계 천체를 구별한다.","url":"labs/solar-objects/"},
  {"id":"density-lab","own":true,"version":1,"missions":4,"subject":"chem","unit":"물질의 특성","grade":"중학교","tags":["sim","data"],"title":"크기가 달라도 같은 물질일까?","desc":"같은 온도의 같은 물질은 양을 바꾸어도 질량과 부피의 비가 같다.","url":"labs/density-lab/"},
  {"id":"solubility-lab","own":true,"version":1,"missions":4,"subject":"chem","unit":"물질의 특성","grade":"중학교","tags":["sim","data"],"title":"녹인 뒤 식히면 무엇이 남을까?","desc":"일정한 온도의 일정량 물에 녹을 수 있는 양에는 한계가 있으며, 냉각으로 용질을 분리할 수 있다.","url":"labs/solubility-lab/"},
  {"id":"mixture-separation","own":true,"version":1,"missions":3,"subject":"chem","unit":"물질의 특성","grade":"중학교","tags":["sim"],"title":"어떤 성질로 나눌 수 있을까?","desc":"혼합물은 성분의 크기·용해·끓는 성질 차이를 이용해 분리한다.","url":"labs/mixture-separation/"},
  {"id":"rock-cycle","own":true,"version":1,"missions":3,"subject":"earth","unit":"지권의 변화","grade":"중학교","tags":["sim"],"title":"암석은 한 방향으로만 바뀔까?","desc":"암석은 생성 과정으로 분류하며 여러 경로로 순환하고 풍화 산물이 토양 형성에 기여한다.","url":"labs/rock-cycle/"},
  {"id":"mineral-tests","own":true,"version":1,"missions":3,"subject":"earth","unit":"지권의 변화","grade":"중학교","tags":["sim"],"title":"겉색이 비슷해도 같은 광물일까?","desc":"색만으로 광물을 확정하지 않고 굳기·조흔색·염산 반응·자성 등 여러 근거를 비교한다.","url":"labs/mineral-tests/"},
  {"id":"plate-patterns","own":true,"version":1,"missions":3,"subject":"earth","unit":"지권의 변화","grade":"중학교","tags":["sim"],"title":"지진과 화산은 아무 곳에나 모일까?","desc":"지진대와 화산대는 대체로 판 경계 부근에 분포하지만 판 내부에도 발생할 수 있다.","url":"labs/plate-patterns/"},
  {"id":"earth-layers","own":true,"version":1,"missions":3,"subject":"earth","unit":"지권의 변화","grade":"중학교","tags":["sim"],"title":"지구 안쪽은 모두 녹아 있을까?","desc":"지각·맨틀·외핵·내핵의 위치와 상태를 구별하고 지구계 구성 요소를 연결한다.","url":"labs/earth-layers/"},
  {"id":"light-paths","own":true,"version":1,"missions":4,"subject":"phys","unit":"빛과 파동","grade":"중학교","tags":["sim","data"],"title":"빛은 경계에서 어디로 갈까?","desc":"빛의 반사각은 입사각과 같고, 물질 경계를 통과할 때 방향이 바뀔 수 있다.","url":"labs/light-paths/"},
  {"id":"image-optics","own":true,"version":1,"missions":3,"subject":"phys","unit":"빛과 파동","grade":"중학교","tags":["sim"],"title":"거울 뒤의 상은 어디에 있을까?","desc":"평면거울의 상은 반사광을 거꾸로 연장한 곳에 보이며 렌즈의 상은 물체 위치에 따라 달라진다.","url":"labs/image-optics/"},
  {"id":"light-colors","own":true,"version":1,"missions":3,"subject":"phys","unit":"빛과 파동","grade":"중학교","tags":["sim"],"title":"같은 물체가 다른 색으로 보일까?","desc":"빛의 합성과 물체가 반사하는 빛을 구별한다.","url":"labs/light-colors/"},
  {"id":"wave-motion","own":true,"version":1,"missions":4,"subject":"phys","unit":"빛과 파동","grade":"중학교","tags":["sim","data"],"title":"파동이 갈 때 입자도 따라갈까?","desc":"매질은 제자리에서 진동하고 파동은 에너지를 전달하며 진폭·진동수·파형은 서로 다르다.","url":"labs/wave-motion/"},
  {"id":"atom-builder","own":true,"version":1,"missions":4,"subject":"chem","unit":"물질의 구성","grade":"중학교","tags":["sim","data"],"title":"원소와 전하는 무엇이 정할까?","desc":"양성자 수가 원소를 정하고, 전자를 얻거나 잃으면 이온이 된다.","url":"labs/atom-builder/"},
  {"id":"reaction-builder","own":true,"version":1,"missions":4,"subject":"chem","unit":"물질의 구성","grade":"중학교","tags":["sim","data"],"title":"다시 짝지어도 원자는 남을까?","desc":"화학 반응은 원자가 다시 결합하는 과정이며 원자 종류와 수가 보존된다.","url":"labs/reaction-builder/"},
  {"id":"periodic-families","own":true,"version":1,"missions":3,"subject":"chem","unit":"물질의 구성","grade":"중학교","tags":["sim"],"title":"원소를 순서대로 놓으면 어떤 무리가 보일까?","desc":"주기율표는 양성자 수 순서로 배치되며 같은 족의 원소는 유사한 성질을 보일 수 있다.","url":"labs/periodic-families/"},
  {"id":"plant-exchange","own":true,"version":1,"missions":4,"subject":"life","unit":"식물과 에너지","grade":"중학교","tags":["sim","data"],"title":"식물은 밤에도 호흡할까?","desc":"광합성과 호흡은 함께 일어나며 바깥에서 측정한 기체 교환은 두 과정의 차이다.","url":"labs/plant-exchange/"},
  {"id":"photosynthesis-conditions","own":true,"version":1,"missions":3,"subject":"life","unit":"식물과 에너지","grade":"중학교","tags":["sim"],"title":"빛만 세게 하면 계속 더 잘될까?","desc":"광합성을 비교하려면 빛·이산화 탄소 등 조건을 통제하며 부족한 요인이 결과를 제한할 수 있다.","url":"labs/photosynthesis-conditions/"},
  {"id":"body-systems","own":true,"version":1,"missions":3,"subject":"life","unit":"동물과 에너지","grade":"중학교","tags":["sim"],"title":"먹은 물질과 들이마신 산소는 어디서 만날까?","desc":"소화·호흡·순환·배설은 세포가 에너지를 얻고 노폐물을 내보내는 과정으로 연결된다.","url":"labs/body-systems/"},
  {"id":"breathing-model","own":true,"version":1,"missions":3,"subject":"life","unit":"동물과 에너지","grade":"중학교","tags":["sim"],"title":"폐가 공기를 밀어 넣는 걸까?","desc":"가로막과 갈비뼈 운동에 따른 가슴 공간 변화가 압력 차이를 만들고 공기가 이동한다.","url":"labs/breathing-model/"},
  {"id":"electric-circuit","own":true,"version":1,"missions":4,"subject":"phys","unit":"전기와 자기","grade":"중학교","tags":["sim","data"],"title":"전류는 전구를 지나면 줄어들까?","desc":"전압과 저항이 전류를 정하며 전류는 직렬 회로에서 이어지고 병렬 회로의 가지에서 나뉜다.","url":"labs/electric-circuit/"},
  {"id":"static-charge","own":true,"version":1,"missions":3,"subject":"phys","unit":"전기와 자기","grade":"중학교","tags":["sim"],"title":"닿지 않았는데 왜 끌려올까?","desc":"전자 이동과 도체 내부 전하 재배치로 대전과 정전기 유도를 구별한다.","url":"labs/static-charge/"},
  {"id":"coil-motor","own":true,"version":1,"missions":4,"subject":"phys","unit":"전기와 자기","grade":"중학교","tags":["sim","data"],"title":"전류를 뒤집으면 힘도 바뀔까?","desc":"자기장 속 코일의 두 변에는 반대 방향의 힘이 작용하며 전류 방향을 바꾸면 힘 방향이 바뀐다.","url":"labs/coil-motor/"},
  {"id":"electrical-energy","own":true,"version":1,"missions":4,"subject":"phys","unit":"전기와 자기","grade":"중학교","tags":["sim","data"],"title":"같은 시간 켜면 같은 에너지를 쓸까?","desc":"소비 전력은 에너지 전환의 빠르기를 나타내며 같은 시간에도 사용하는 에너지가 다를 수 있다.","url":"labs/electrical-energy/"},
  {"id":"star-distance","own":true,"version":1,"missions":4,"subject":"earth","unit":"별과 우주","grade":"중학교","tags":["sim","data"],"title":"밝게 보이는 별이 정말 더 밝을까?","desc":"별의 겉보기 밝기는 실제 광도와 거리에 함께 의존하며 가까운 별의 시차가 더 크다.","url":"labs/star-distance/"},
  {"id":"expanding-space","own":true,"version":1,"missions":4,"subject":"earth","unit":"별과 우주","grade":"중학교","tags":["sim","data"],"title":"어느 은하에서 보아도 멀어질까?","desc":"공간의 팽창 모형에서는 은하 사이 거리가 늘어나며 특정 은하를 팽창 중심으로 정할 수 없다.","url":"labs/expanding-space/"},
  {"id":"galaxy-structure","own":true,"version":1,"missions":3,"subject":"earth","unit":"별과 우주","grade":"중학교","tags":["sim"],"title":"은하를 안에서 보면 왜 띠처럼 보일까?","desc":"우리은하는 원반 구조를 가지며 그 안에 있는 관측자는 원반 방향에서 별이 모인 띠를 본다.","url":"labs/galaxy-structure/"},
  {"id":"reaction-energy","own":true,"version":1,"missions":4,"subject":"chem","unit":"화학 반응의 규칙성","grade":"중학교","tags":["sim","data"],"title":"반응할 때 주변은 따뜻해질까?","desc":"발열 반응은 주변으로 에너지를 전달하고 흡열 반응은 주변에서 에너지를 받는다.","url":"labs/reaction-energy/"},
  {"id":"humidity-cloud","own":true,"version":1,"missions":4,"subject":"earth","unit":"날씨와 기후변화","grade":"중학교","tags":["sim","data"],"title":"수증기가 늘지 않아도 습해질까?","desc":"기온이 내려가면 포화 수증기압이 낮아져 상대습도가 커지며 포화 이후 응결할 수 있다.","url":"labs/humidity-cloud/"},
  {"id":"radiation-balance","own":true,"version":1,"missions":4,"subject":"earth","unit":"날씨와 기후변화","grade":"중학교","tags":["sim","data"],"title":"받는 에너지와 나가는 에너지가 달라지면?","desc":"복사 평형은 들어오는 에너지와 나가는 에너지의 균형이며 온실효과는 지표 복사의 흡수·재방출과 관련된다.","url":"labs/radiation-balance/"},
  {"id":"weather-fronts","own":true,"version":1,"missions":3,"subject":"earth","unit":"날씨와 기후변화","grade":"중학교","tags":["sim"],"title":"공기가 만나는 방식이 날씨를 바꿀까?","desc":"고기압·저기압의 공기 이동과 전선에서 따뜻한 공기의 상승을 연결한다.","url":"labs/weather-fronts/"},
  {"id":"ocean-circulation","own":true,"version":1,"missions":3,"subject":"earth","unit":"날씨와 기후변화","grade":"중학교","tags":["sim"],"title":"바람과 해류는 열을 어디로 옮길까?","desc":"바람과 북태평양 표층 해류가 연결되고 해류는 저위도와 고위도 사이 에너지를 재분배한다.","url":"labs/ocean-circulation/"},
  {"id":"atmosphere-circulation","own":true,"version":1,"missions":3,"subject":"earth","unit":"날씨와 기후변화","grade":"중학교","tags":["sim"],"title":"높이와 위도를 바꾸면 공기는 어떻게 다를까?","desc":"대기의 수직 층과 위도별 지표 바람을 구별하고 대순환이 에너지 재분배에 기여함을 이해한다.","url":"labs/atmosphere-circulation/"},
  {"id":"ocean-salinity","own":true,"version":1,"missions":4,"subject":"earth","unit":"수권과 해수의 순환","grade":"중학교","tags":["sim","data"],"title":"물만 증발하면 염분은 어떻게 될까?","desc":"해수의 염분은 전체 해수 질량 중 염류의 질량 비율이며 물의 유출입으로 변한다.","url":"labs/ocean-salinity/"},
  {"id":"motion-energy","own":true,"version":1,"missions":4,"subject":"phys","unit":"운동과 에너지","grade":"중학교","tags":["sim","data"],"title":"떨어지는 동안 에너지는 어디로 갈까?","desc":"자유 낙하에서 속력은 같은 시간마다 같은 만큼 늘고 위치 에너지가 운동 에너지로 전환된다.","url":"labs/motion-energy/"},
  {"id":"motion-graphs","own":true,"version":1,"missions":4,"subject":"phys","unit":"운동과 에너지","grade":"중학교","tags":["sim","data"],"title":"그래프 모양이 곧 이동 경로일까?","desc":"시간–거리 그래프의 기울기와 시간–속력 그래프를 실제 직선 운동에 연결한다.","url":"labs/motion-graphs/"},
  {"id":"neural-response","own":true,"version":1,"missions":3,"subject":"life","unit":"자극과 반응","grade":"중학교","tags":["sim"],"title":"반응은 어떤 길을 거쳐 나올까?","desc":"감각기관의 자극은 신경을 통해 중추로 전달되고 반응 명령이 운동기관으로 전달된다.","url":"labs/neural-response/"},
  {"id":"hormone-balance","own":true,"version":1,"missions":3,"subject":"life","unit":"자극과 반응","grade":"중학교","tags":["sim"],"title":"혈당이 달라지면 몸은 어떻게 조절할까?","desc":"호르몬은 혈액을 통해 표적 기관에 작용하며 혈당 변화에 대한 조절이 항상성에 기여한다.","url":"labs/hormone-balance/"},
  {"id":"cell-division","own":true,"version":1,"missions":4,"subject":"life","unit":"생식과 유전","grade":"중학교","tags":["sim","data"],"title":"세포는 왜 커지기만 하지 않을까?","desc":"세포 크기에 따른 표면적과 부피의 관계, 분열에 따른 염색체 분배를 구별한다.","url":"labs/cell-division/"},
  {"id":"inheritance-lab","own":true,"version":1,"missions":4,"subject":"life","unit":"생식과 유전","grade":"중학교","tags":["sim","data"],"title":"우성 형질은 언제나 더 많을까?","desc":"자손은 부모에게서 대립유전자를 하나씩 받으며 확률은 가족 수가 적을 때 정확한 비율을 보장하지 않는다.","url":"labs/inheritance-lab/"},

  // ───────── 물리 · 빛과 파동
  { id:'lw01', subject:'phys', unit:'빛과 파동', grade:'중2', tags:['sim','game'],
    title:'빛의 반사와 굴절', desc:'레이저를 쏘아 반사·굴절 법칙을 찾고, 미로·포켓볼·물총고기로 써 봅니다.',
    url:LW+'01.html', shot:LW+'01.html#reflCanvas', parts:[
      ['반사', LW+'01.html#reflCanvas'], ['굴절', LW+'01.html#refrCanvas'], ['레이저 미로', LW+'01.html#mazeCanvas'],
      ['페르마의 원리', LW+'01.html#whyFermatCanvas'], ['호이겐스 반사', LW+'01.html#whyHuyCanvas'], ['호이겐스 굴절', LW+'01.html#whyRefrHuyCanvas'],
      ['전자 재방출', LW+'01.html#whyEmCanvas'], ['마차 비유', LW+'01.html#wagonFrame'], ['Light Soccer', LW+'01.html#soccerFrame'],
      ['빛 포켓볼', LW+'01.html#poolFrame'], ['물총고기', LW+'01.html#fishFrame'] ] },
  { id:'lw02', subject:'phys', unit:'빛과 파동', grade:'중2', tags:['sim','3d'],
    title:'평면거울 탐정', desc:'거울 속 상의 위치를 맞히고, 좌우가 아니라 앞뒤가 뒤집힌다는 것을 3D로 확인합니다.',
    url:LW+'02.html', shot:LW+'02.html#featCanvas', parts:[
      ['거울 탐정', LW+'02.html#featCanvas'], ['상 위치 맞히기', LW+'02.html#quizCanvas'], ['빛의 경로 3단계', LW+'02.html#rayCanvas'],
      ['6단계 광원 추적', LW+'02.html#storyCanvas'], ['거울 속 글자 3D', LW+'02.html#mir3d'], ['좌표축 반전 3D', LW+'02.html#coord3d'],
      ['F 앞뒤 반전', LW+'02.html#depthCanvas'], ['빛의 길 잇기', LW+'02.html#ptCanvas'], ['검수관 2D', LW+'02.html#inspCanvas'],
      ['검수관 3D', LW+'02.html#insp3d'], ['빛다발', LW+'02.html#whyBundleCanvas'], ['경로 펼치기', LW+'02.html#whyBrainCanvas'],
      ['합동 증명', LW+'02.html#whyProofCanvas'], ['전신거울 길이', LW+'02.html#whyHalfCanvas'], ['두 거울 무한 반사', LW+'02.html#whyTwoCanvas'],
      ['얼굴 반전', LW+'02.html#faceCanvas'], ['오른손 들기', LW+'02.html#handCanvas'] ] },
  { id:'lw03', subject:'phys', unit:'빛과 파동', grade:'중2', tags:['sim'],
    title:'거울과 렌즈의 모양', desc:'볼록·오목 거울의 시야를 비교하고 렌즈를 깎아 빛이 모이는 모양을 만듭니다.',
    url:LW+'03.html', shot:LW+'03.html#mirCanvas', parts:[
      ['시야 비교기', LW+'03.html#mirCanvas'], ['렌즈 공방', LW+'03.html#shapeCanvas'], ['렌즈 너머 보기', LW+'03.html#lookCanvas'] ] },
  { id:'lw04', subject:'phys', unit:'빛과 파동', grade:'중2', tags:['sim'],
    title:'거울과 렌즈에 의한 상', desc:'물체를 옮기며 상의 크기·방향이 바뀌는 순간을 찾고, 꺾인 연필과 떠오르는 동전을 풀어 봅니다.',
    url:LW+'04.html', shot:LW+'04.html#lnCanvas', parts:[
      ['거울 관찰 카메라', LW+'04.html#mirCanvas'], ['렌즈 관찰 카메라', LW+'04.html#lenCanvas'], ['빛의 여행', LW+'04.html#rcCanvas'],
      ['광학 수사대', LW+'04.html#gmCanvas'], ['초점 찾기', LW+'04.html#fcCanvas'], ['볼록거울 시야', LW+'04.html#bvCanvas'],
      ['오목거울', LW+'04.html#cvCanvas'], ['상과 연장선', LW+'04.html#miCanvas'], ['렌즈의 상', LW+'04.html#lnCanvas'],
      ['수정체 조절', LW+'04.html#accCanvas'], ['호수에 비친 구름', LW+'04.html#rflCanvas'], ['물속 굴절', LW+'04.html#rfrCanvas'],
      ['꺾인 연필', LW+'04.html#pencCanvas'], ['떠오르는 동전', LW+'04.html#coinCanvas'], ['두 번 굴절', LW+'04.html#trCanvas'],
      ['근시와 원시', LW+'04.html#eyCanvas'] ] },
  { id:'lw05', subject:'phys', unit:'빛과 파동', grade:'중2', tags:['sim'],
    title:'빛의 합성과 색', desc:'빛의 삼원색을 섞어 화면 속 색을 만들고, 물감이 섞일 때와 무엇이 다른지 비교합니다.',
    url:LW+'05.html', shot:LW+'05.html#clCanvas', parts:[
      ['통합 색 실험실', LW+'05.html#clCanvas'], ['RGB 섞기', LW+'05.html#cvRgb'], ['비트맵 송출', LW+'05.html#cv3'],
      ['LCD 확대', LW+'05.html#cv4'], ['원뿔세포', LW+'05.html#cvCone'], ['조건등색', LW+'05.html#cvMeta'],
      ['감산 혼합', LW+'05.html#cvSub'], ['흡수 원리', LW+'05.html#cvAbs'], ['색 퀴즈', LW+'05.html#cvQuiz'],
      ['빛 그림판', LW+'05.html#cvPaint'], ['강아지의 눈', LW+'05.html#cvDogSpec'], ['갯가재의 눈', LW+'05.html#cvMantis'] ] },
  { id:'wave01', subject:'phys', unit:'빛과 파동', grade:'중2', tags:['sim'],
    title:'파동의 발생과 전달', desc:'용수철을 흔들어 파동을 만들고 파장·진폭을 직접 재 봅니다.',
    url:LW+'wave01.html', shot:LW+'wave01.html#springCv', parts:[
      ['지진파', LW+'wave01.html#quakeCv'], ['울음 파형', LW+'wave01.html#roarCv'], ['용수철 파동', LW+'wave01.html#springCv'],
      ['파동 해부도', LW+'wave01.html#anatomyCv'], ['파장 측정', LW+'wave01.html#measCv'] ] },
  { id:'wave02', subject:'phys', unit:'빛과 파동', grade:'중2', tags:['sim','game'],
    title:'소리의 세 요소', desc:'오실로스코프로 크기·높낮이·음색을 파형으로 보고, 소리 형사가 되어 파형을 맞힙니다.',
    url:LW+'wave02.html', shot:LW+'wave02.html#scopeMain', parts:[
      ['오실로스코프', LW+'wave02.html#scopeMain'], ['파장과 진동수', LW+'wave02.html#wlCanvas'], ['악보 예측', LW+'wave02.html#poeRefCanvas'],
      ['파형 맞추기', LW+'wave02.html#matchTargetCanvas'], ['소리 형사', LW+'wave02.html#quizCanvas'], ['배음', LW+'wave02.html#harmCanvas'] ] },
  { id:'soundpokedex', subject:'phys', unit:'빛과 파동', grade:'중2', tags:['sim','game','mic'],
    title:'소리 도감', desc:'마이크로 목소리의 파형과 진동수를 실시간으로 잡고, 친구와 고음·저음 배틀을 합니다.',
    url:LW+'sound-pokedex.html' },
  { id:'voicequest', subject:'phys', unit:'빛과 파동', grade:'중2', tags:['sim','mic'],
    title:'소리 탐정단', desc:'내 목소리를 녹음해 파형에서 파동의 세 요소를 찾아냅니다.',
    url:LW+'voice-quest.html' },
  { id:'pitchtest', subject:'phys', unit:'빛과 파동', grade:'중2', tags:['game'],
    title:'절대음감 테스트', desc:'들려주는 음의 진동수를 맞히며 높낮이와 진동수의 관계를 익힙니다.',
    url:LW+'pitch-test.html' },
  { id:'flip', subject:'phys', unit:'빛과 파동', grade:'중2', tags:['cam','game'],
    title:'좌우반전 챌린지', desc:'웹캠으로 내 얼굴을 비춰 거울상이 정말 좌우만 바뀌는지 따져 봅니다.',
    url:LW+'flipchallenge.html' },
  { id:'amplitude', subject:'phys', unit:'빛과 파동', grade:'중2', tags:['sim','game'],
    title:'진폭 챌린지', desc:'목표 파형과 같은 크기의 소리를 만들어 진폭과 소리 크기의 관계를 찾습니다.',
    url:B+'test02/' },
  { id:'hologram', subject:'phys', unit:'빛과 파동', grade:'중2', tags:['sim','3d'],
    title:'3D 홀로그램', desc:'피라미드 홀로그램 속 영상이 떠 보이는 까닭을 반사의 법칙으로 풀고 직접 만들어 봅니다.',
    url:B+'hologram/', parts:[['홀로그램 시뮬', B+'hologram/'], ['홀로그램 연구소', B+'hologram/new.html'], ['만들기 실습', B+'hologram/making.html']] },

  // ───────── 물리 · 전기와 자기
  { id:'sparkle', subject:'phys', unit:'전기와 자기', grade:'중2', tags:['game','3d'],
    title:'놀러오세요 전기의 숲', desc:'섬 주민의 부탁을 들어주며 회로를 잇고, 옴의 법칙과 직렬·병렬을 직접 풀어 갑니다.',
    url:EL+'sparkle-island/', thumb:EL+'sparkle-island/art/cover-island.png' },
  { id:'electric-friction', subject:'phys', unit:'전기와 자기', grade:'중2', tags:['sim'],
    title:'마찰 전기 모형', desc:'두 물체를 문지를 때 전자가 어느 쪽으로 옮겨 가는지 모형으로 봅니다.',
    url:EL+'01-friction.html?tab=model' },
  { id:'induction', subject:'phys', unit:'전기와 자기', grade:'중2', tags:['sim'],
    title:'정전기 유도', desc:'대전체를 가까이 대면 금속 캔 속 전하가 갈라지는 모습을 거리·재질을 바꿔 봅니다.',
    url:EL+'02-induction.html?tab=model' },
  { id:'electrophorus', subject:'phys', unit:'전기와 자기', grade:'중2', tags:['sim'],
    title:'정전기 실험실', desc:'전지 없이 마찰로 모은 전하만으로 전구를 켜 봅니다.',
    url:EL+'ask-electrophorus.html' },
  { id:'circuit', subject:'phys', unit:'전기와 자기', grade:'중2', tags:['sim'],
    title:'회로 잇기', desc:'회로판에 도선을 이어 전구가 켜지는 조건을 찾습니다.',
    url:EL+'ask-circuit.html' },
  { id:'current', subject:'phys', unit:'전기와 자기', grade:'중2', tags:['sim'],
    title:'전류의 두 손잡이', desc:'전압과 저항 슬라이더로 전류의 세기가 정해지는 방식을 보고, 전자와 전류의 방향을 비교합니다.',
    url:EL+'03-current.html?tab=vr', parts:[['전압과 저항', EL+'03-current.html?tab=vr'], ['전류의 방향', EL+'03-current.html?tab=direction']] },
  { id:'ohm', subject:'phys', unit:'전기와 자기', grade:'중2', tags:['sim','data'],
    title:'옴의 실험대', desc:'전압과 니크롬선 길이를 바꿔 전류계를 읽고, 표의 값을 그래프에 찍어 봅니다.',
    url:EL+'04-ohm.html?tab=explore' },
  { id:'seriesparallel', subject:'phys', unit:'전기와 자기', grade:'중2', tags:['sim'],
    title:'직렬과 병렬', desc:'전구 두 개를 한 줄로, 나란히 잇고 하나를 빼 보며 밝기를 비교합니다.',
    url:EL+'05-series-parallel.html?tab=compare' },
  { id:'power', subject:'phys', unit:'전기와 자기', grade:'중2', tags:['sim'],
    title:'전기 에너지의 전환', desc:'전기 에너지가 빛·열·소리·운동 에너지로 갈라지는 흐름을 봅니다.',
    url:EL+'06-power.html' },
  { id:'coil', subject:'phys', unit:'전기와 자기', grade:'중2', tags:['sim'],
    title:'코일과 나침반', desc:'전류의 방향·세기·감은 수를 바꾸며 나침반 바늘이 어디를 가리키는지 봅니다.',
    url:EL+'07-coil-field.html?tab=explore' },
  { id:'motor', subject:'phys', unit:'전기와 자기', grade:'중2', tags:['sim'],
    title:'전동기와 스피커', desc:'자석 사이 코일이 받는 힘으로 회전과 진동이 만들어지는 구조를 뜯어봅니다.',
    url:EL+'08-motor.html?tab=explore', parts:[['힘 실험대', EL+'08-motor.html?tab=explore'], ['전동기·스피커 뜯어보기', EL+'08-motor.html?tab=mech']] },
  { id:'righthand', subject:'phys', unit:'전기와 자기', grade:'중2', tags:['sim','3d'],
    title:'오른손 규칙 3D', desc:'손을 돌려 가며 전류와 자기장의 방향 관계를 입체로 익힙니다.',
    url:EL+'3d-righthand.html' },
  { id:'emind', subject:'phys', unit:'전기와 자기', grade:'중2', tags:['sim','3d'],
    title:'전자기 유도와 발전기', desc:'자석을 코일에 넣었다 빼며 전류가 생기는 조건을 3D로 찾습니다.',
    url:EL+'3d-induction.html' },
  { id:'stembooth', subject:'phys', unit:'반도체·전기', grade:'축제 부스', tags:['sim','game'],
    title:'어쩌다 반도체 연구원', desc:'전기·자기·반도체 미션 여섯 개를 풀며 연구원 자격을 얻습니다.',
    url:B+'stem-booth/lab.html', thumb:B+'stem-booth/plan/img/banner.png', parts:[
      ['m1 손잡고 불 켜라', B+'stem-booth/m1.html'], ['m2 캔을 움직여라', B+'stem-booth/m2.html'], ['m3 불빛을 깨워라', B+'stem-booth/m3.html'],
      ['m4 내 몸을 돌려라', B+'stem-booth/m4.html'], ['m5 건전지야 달려!', B+'stem-booth/m5.html'], ['m6 기억을 만들어라', B+'stem-booth/m6.html'] ] },

  // ───────── 생명 (다른 단원 속 감각 기관 시뮬)
  { id:'senses', subject:'life', unit:'자극과 반응', grade:'중학', tags:['sim'],
    title:'눈과 귀의 과학', desc:'수정체 조절·근시와 원시·원뿔세포·동물의 눈·귀 구조를 한곳에 모았습니다.',
    url:LW+'04.html#accCanvas', parts:[
      ['수정체 조절', LW+'04.html#accCanvas'], ['근시와 원시', LW+'04.html#eyCanvas'], ['원뿔세포', LW+'05.html#cvCone'],
      ['강아지의 눈', LW+'05.html#cvDogSpec'], ['갯가재의 눈', LW+'05.html#cvMantis'], ['귀의 구조', LW+'wave02.html#earSvg'] ] },

  // ───────── 화학 · 기체의 성질
  { id:'gas1', subject:'chem', unit:'기체의 성질', grade:'중1', tags:['sim'],
    title:'스펀지 압력 실험대', desc:'누르는 힘과 닿는 면적을 따로 바꿔 압력이 무엇에 달렸는지 확인합니다.',
    url:GA+'01-pressure.html?tab=explore' },
  { id:'gas2', subject:'chem', unit:'기체의 성질', grade:'중1', tags:['sim'],
    title:'기체의 압력과 입자', desc:'쇠구슬 페트병과 입자 상자로 기체 압력이 입자의 충돌이라는 것을 봅니다.',
    url:GA+'02-gas-pressure.html?tab=model', parts:[['쇠구슬 페트병 모형', GA+'02-gas-pressure.html?tab=explore'], ['입자 상자 충돌 세기', GA+'02-gas-pressure.html?tab=model']] },
  { id:'gas3', subject:'chem', unit:'기체의 성질', grade:'중1', tags:['sim','sensor','data'],
    title:'압력과 부피 (보일 법칙)', desc:'주사기를 눌러 압력을 읽고, 피스톤 입자 상자로 충돌이 늘어나는 까닭을 봅니다.',
    url:GA+'03-boyle.html?tab=model', parts:[['주사기와 압력 센서', GA+'03-boyle.html?tab=mbl'], ['피스톤 입자 상자', GA+'03-boyle.html?tab=model']] },
  { id:'gas4', subject:'chem', unit:'기체의 성질', grade:'중1', tags:['sim','data'],
    title:'온도와 부피 (샤를 법칙)', desc:'스포이트 물방울로 부피를 재고, 입자가 빨라지며 피스톤이 밀려 올라가는 모형을 봅니다.',
    url:GA+'04-charles.html?tab=model', parts:[['스포이트 물방울', GA+'04-charles.html?tab=explore'], ['자유 피스톤 입자 상자', GA+'04-charles.html?tab=model']] },

  // ───────── 화학 · 물질의 구성
  { id:'atom', subject:'chem', unit:'물질의 구성', grade:'중학', tags:['sim','game'],
    title:'원자 제작소', desc:'양성자·중성자·전자를 조립해 원자를 만들고 족의 규칙을 찾습니다.',
    url:B+'atomicnumber/' },
  { id:'electrolysis', subject:'chem', unit:'물질의 구성', grade:'중학', tags:['sim'],
    title:'물의 전기 분해', desc:'물을 전기 분해해 나온 기체를 확인하며 원소와 화합물을 구별합니다.',
    url:B+'element_compound/' },
  { id:'restaurant', subject:'chem', unit:'물질의 구성', grade:'중학', tags:['sim','game'],
    title:'입자 레스토랑', desc:'분자 꼬치를 굽고 이온을 만들어 소금 결정을 쌓습니다.',
    url:B+'particlerestaurant/' },
  { id:'ionkerby', subject:'chem', unit:'물질의 구성', grade:'중학', tags:['game'],
    title:'이온 커비', desc:'전자를 쏘고 삼키며 양이온과 음이온을 만들어 봅니다.',
    url:B+'ionicmovement/ionkerby.html' },
  { id:'ionmove', subject:'chem', unit:'물질의 구성', grade:'중학', tags:['sim'],
    title:'이온의 이동', desc:'거름종이 위의 이온이 전극을 따라 움직이는 모습을 봅니다.',
    url:B+'ionicmovement/', parts:[['이온의 이동', B+'ionicmovement/'], ['이온 이동 가상 실험', B+'ioncircle/']] },
  { id:'ptable', subject:'chem', unit:'물질의 구성', grade:'중학', tags:['game'],
    title:'마법의 원소 지도', desc:'주기율표가 만들어진 역사를 퍼즐로 따라갑니다.',
    url:B+'periodictable/' },
  { id:'battery', subject:'chem', unit:'전지와 이온', grade:'심화', tags:['sim'],
    title:'리튬이온전지 탐험', desc:'충전과 방전 때 전지 속 리튬 이온이 어느 쪽으로 옮겨 가는지 봅니다.',
    url:B+'lithumbattery/' },

  // ───────── 화학 · 물질의 특성
  { id:'densitydetective', subject:'chem', unit:'물질의 특성', grade:'중학', tags:['sim','game'],
    title:'밀도 탐정 사건 파일', desc:'질량과 부피를 재서 밀도로 범인 물질을 가려냅니다.',
    url:PM },
  { id:'puremix', subject:'chem', unit:'물질의 특성', grade:'중학', tags:['sim','game'],
    title:'순물질과 혼합물', desc:'달걀 소금물과 가열 그래프로 순물질과 혼합물의 차이를 예상하고 확인합니다.',
    url:PM+'puremixture.html', parts:[['순물질과 혼합물', PM+'puremixture.html'], ['입자 쟁탈전', PM+'puremixturefight.html']] },
  { id:'bpmp', subject:'chem', unit:'물질의 특성', grade:'중학', tags:['sim','data'],
    title:'녹는점과 끓는점', desc:'가열·냉각 곡선을 직접 그리고 평평한 구간이 무엇인지 찾습니다.',
    url:PM+'bpmp.html' },
  { id:'solubility', subject:'chem', unit:'물질의 특성', grade:'중학', tags:['sim','data'],
    title:'용해도 실험실', desc:'온도를 바꿔 녹이고 결정을 석출하며 용해도 곡선을 그립니다.',
    url:PM+'solubility.html' },
  { id:'snoop', subject:'chem', unit:'물질의 특성', grade:'중학', tags:['game','data'],
    title:'물질 추리 탐정', desc:'밀도·녹는점·용해도 자료를 모아 정체 모를 물질을 감별합니다.',
    url:PM+'mattersnoop.html' },
  { id:'densitytower', subject:'chem', unit:'물질의 특성', grade:'중학', tags:['sim'],
    title:'밀도 탑', desc:'온도를 정하고 여러 액체를 부어 밀도 순서대로 층을 쌓습니다.',
    url:B+'density-tower-lab/' },
  { id:'atelier', subject:'chem', unit:'혼합물의 분리', grade:'중학', tags:['game'],
    title:'밀도 공방 Density Atelier', desc:'재료의 밀도를 따져 층이 섞이지 않는 음료를 만듭니다.',
    url:B+'density-atelier/', parts:[['밀도 공방', B+'density-atelier/'], ['재료 창고', B+'density-atelier/warehouse.html']] },
  { id:'separation', subject:'chem', unit:'혼합물의 분리', grade:'중학', tags:['sim','game'],
    title:'혼합물 분리 실험실', desc:'밀도·용해도·끓는점·녹는점 차이로 섞인 물질을 하나씩 갈라냅니다.',
    url:SE, thumb:SE+'images/witch-lab-bg.png', parts:[
      ['밀도 차 분리', SE+'density.html'], ['용해도 차 분리', SE+'solubility.html'], ['분별 결정', SE+'crystallization.html'],
      ['끓는점 차 분리', SE+'boiling.html'], ['분별 증류', SE+'distillation.html'], ['녹는점 분리 (제련소)', SE+'melting.html'],
      ['종합 분리 실험실', SE+'finallab.html'] ] },
  { id:'lemon', subject:'chem', unit:'산과 염기', grade:'고1', tags:['game','3d'],
    title:'레몬 백작의 부탁', desc:'과학의 섬을 돌아다니며 지시약과 중화 반응으로 마을의 문제를 풉니다.',
    url:B+'science-islands/lemon-island/' },

  // ───────── 지구 · 태양계
  { id:'planets', subject:'earth', unit:'태양계', grade:'중1', tags:['data'],
    title:'행성의 두 집단', desc:'축을 골라 행성 자료를 산점도로 그리고 선을 그어 두 집단으로 나눕니다.',
    url:SO+'03-two-groups.html?tab=read' },
  { id:'sunspot', subject:'earth', unit:'태양계', grade:'중1', tags:['sim'],
    title:'흑점은 왜 검을까', desc:'어두운 것과 덜 밝은 것의 차이를 온도 모형으로 봅니다.',
    url:SO+'04-sun-surface.html?tab=model' },
  { id:'rotation', subject:'earth', unit:'태양계', grade:'중1', tags:['sim'],
    title:'자전과 일주 운동', desc:'우주에서 본 지구와 땅에서 본 하늘을 나란히 돌려 봅니다.',
    url:SO+'06-rotation.html?tab=sim' },
  { id:'revolution', subject:'earth', unit:'태양계', grade:'중1', tags:['sim'],
    title:'공전과 계절별 별자리', desc:'지구의 공전 위치를 옮기며 한밤중에 보이는 별자리가 바뀌는 까닭을 찾습니다.',
    url:SO+'07-revolution.html?tab=model' },
  { id:'moonphase', subject:'earth', unit:'태양계', grade:'중1', tags:['sim'],
    title:'달의 위상', desc:'달을 궤도 위에서 옮기며 지구에서 보이는 모양을 맞혀 봅니다.',
    url:SO+'08-moon-phase.html?tab=model' },
  { id:'eclipse', subject:'earth', unit:'태양계', grade:'중1', tags:['sim'],
    title:'일식과 월식', desc:'태양·지구·달을 한 줄로 세워 그림자를 만들고, 2035년 한반도 일식 지도를 봅니다.',
    url:SO+'09-eclipse.html?tab=model', parts:[['그림자 모형', SO+'09-eclipse.html?tab=model'], ['2035 한반도 지도', SO+'09-eclipse.html?tab=map']] },

  // ───────── 지구 · 별과 우주
  { id:'parallax', subject:'earth', unit:'별과 우주', grade:'중2', tags:['sim'],
    title:'연주 시차', desc:'지구를 반년 돌려 가까운 별과 먼 별 중 어느 쪽이 더 흔들려 보이는지 잽니다.',
    url:ST+'01-parallax.html?tab=explore', thumb:ST+'img/hub-l1.png', parts:[['연주 시차 시뮬레이터', ST+'01-parallax.html?tab=explore'], ['두 눈 시차', ST+'01-parallax.html?tab=apply'], ['연주 시차 3D 우주', ST+'3d-parallax.html']] },
  { id:'brightness', subject:'earth', unit:'별과 우주', grade:'중2', tags:['sim','data'],
    title:'별의 밝기와 거리', desc:'빛이 퍼지는 면적을 세어 밝기가 거리의 제곱에 반비례한다는 것을 찾습니다.',
    url:ST+'02-brightness.html?tab=explore', thumb:ST+'img/hub-l2.png', parts:[['빛 퍼짐 시뮬', ST+'02-brightness.html?tab=explore'], ['면적 격자', ST+'02-brightness.html?tab=explain']] },
  { id:'magnitude', subject:'earth', unit:'별과 우주', grade:'중2', tags:['sim'],
    title:'등급 밝기 비교기', desc:'등급이 5 차이 나면 밝기가 100배 차이 난다는 것을 별을 놓고 비교합니다.',
    url:ST+'03-magnitude.html?tab=compare', thumb:ST+'img/hub-l3.png' },
  { id:'starcolor', subject:'earth', unit:'별과 우주', grade:'중2', tags:['sim'],
    title:'별의 색과 온도', desc:'다이얼을 돌려 표면 온도에 따라 별의 색이 어떻게 바뀌는지 봅니다.',
    url:ST+'04-color.html?tab=observe', thumb:ST+'img/hub-l4.png' },
  { id:'milkyway', subject:'earth', unit:'별과 우주', grade:'중2', tags:['sim','3d'],
    title:'우리은하 관측소', desc:'세 시점을 오가며 은하수가 하늘에 띠로 보이는 까닭을 찾습니다.',
    url:ST+'05-milkyway.html?tab=model', thumb:ST+'img/hub-l5.png', parts:[['우리은하 관측소', ST+'05-milkyway.html?tab=model'], ['은하수 관측소 3D', ST+'3d-milkyway.html']] },
  { id:'expanding', subject:'earth', unit:'별과 우주', grade:'중2', tags:['sim','data'],
    title:'풍선 우주', desc:'풍선을 불며 멀리 있는 은하일수록 더 빨리 멀어진다는 것을 재 봅니다.',
    url:ST+'08-expanding.html?tab=explore', thumb:ST+'img/hub-l8.png' },

  // ───────── 지구 · 지권의 변화
  { id:'earthlayers', subject:'earth', unit:'지권의 변화', grade:'중학', tags:['sim','game'],
    title:'지구 탐험대', desc:'시추와 지진파 자료로 직접 볼 수 없는 지구 속 층 구조를 추리합니다.',
    url:B+'-layered-structure-of-the-earth/' },
  { id:'mineral', subject:'earth', unit:'지권의 변화', grade:'중학', tags:['sim'],
    title:'광물 실험실', desc:'굳기·염산 반응·자성을 시험해 광물을 가려냅니다.',
    url:B+'minerallab/' },
  { id:'igneous', subject:'earth', unit:'지권의 변화', grade:'중학', tags:['game'],
    title:'화성암의 여행', desc:'마그마가 식은 위치와 빠르기로 화성암을 분류합니다.',
    url:B+'scienceworld/igneousrocks.html' },
  { id:'sedimentary', subject:'earth', unit:'지권의 변화', grade:'중학', tags:['game'],
    title:'퇴적암의 여행', desc:'풍화·운반·퇴적·다짐을 차례로 거쳐 퇴적암을 만듭니다.',
    url:B+'sedimentaryrock-adventure/' },
  { id:'metamorphic', subject:'earth', unit:'지권의 변화', grade:'중학', tags:['game'],
    title:'변성암 베이커리', desc:'열과 압력 오븐을 조절해 원래 암석을 변성암으로 구워 냅니다.',
    url:B+'metamorphic-rock/' },
  { id:'rockclass', subject:'earth', unit:'지권의 변화', grade:'중학', tags:['game'],
    title:'암석 분류 알고리즘', desc:'질문을 이어 붙여 어떤 암석이든 가려내는 분류 순서도를 완성합니다.',
    url:B+'rock-classification/' },
  { id:'earthbalance', subject:'earth', unit:'지구계', grade:'중학', tags:['game'],
    title:'어스밸런스', desc:'재난 카드가 지구계의 여러 권역으로 번져 가는 연쇄를 막아 냅니다.',
    url:B+'scienceworld/earthbalance.html' },
  { id:'netzero', subject:'earth', unit:'기후와 환경', grade:'자율 탐구', tags:['sim','game'],
    title:'NET ZERO 2050', desc:'도시의 에너지와 교통을 골라 2050년 탄소 중립에 닿을 수 있는지 시험합니다.',
    url:B+'ai-science-it/' },
  { id:'salinity', subject:'earth', unit:'해수의 성질', grade:'영재', tags:['sim','data'],
    title:'간이 염분계 보정 탐구', desc:'굴절과 부력으로 염분을 재는 원리를 시뮬로 보고 보정 그래프를 그립니다.',
    url:B+'gifted-science/salinity-main.html', parts:[['보정 탐구', B+'gifted-science/salinity.html'], ['간이 염분 측정기 시뮬', B+'portfolio/salinity-sim.html']] },

  // ───────── 센서로 재는 실험
  { id:'mbl', subject:'phys', unit:'센서 실험', grade:'중학', tags:['sensor','data'],
    title:'MBL 센서 수업허브', desc:'센서 실험 38건을 모둠별로 진행하고, 센서가 없을 때는 탐구 모드로 합니다.',
    url:B+'mblclasshub/', thumb:B+'mblclasshub/assets/hero.webp', parts:[['수업허브', B+'mblclasshub/'], ['센서 없이 탐구', B+'mblclasshub/inquiry.html']] },
  { id:'ezdash', subject:'phys', unit:'센서 실험', grade:'중학', tags:['sensor','data'],
    title:'이지메이커 실험 대시보드', desc:'밝기 센서와 초음파 거리 센서 값을 받아 실시간 그래프로 봅니다.',
    url:B+'teacher-toolkit/experiment-dashboard/' },
];
