const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),pp=require(process.env.PUPPETEER_PATH||'puppeteer-core');const out=process.env.TEST_OUTPUT||path.resolve('test-results/bimetal-switch');fs.mkdirSync(out,{recursive:true});const result={numbers:[],missions:[],screenshots:[],errors:[]};let browser;const near=(a,b,e=1e-9)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
(async()=>{browser=await pp.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const p=await browser.newPage();p.on('pageerror',e=>result.errors.push(e.message));p.on('console',m=>{if(m.type()==='error')result.errors.push(m.text());});const url='http://127.0.0.1:7101/labs/bimetal-switch/';await p.setViewport({width:1920,height:1080});
for(const mode of ['model','learn']){await p.goto(url+'?mode='+mode);await p.waitForFunction(()=>window.lab);const values=await p.evaluate(()=>Object.keys(MAT).flatMap(upper=>Object.keys(MAT).flatMap(lower=>[-20,0,20,80,150].map(T=>{const s={upper,lower};return {upper,lower,T,delta:deflect(s,T)};}))));for(const r of values){const a={al:23,brass:19,cu:17,iron:11};near(r.delta,3*(a[r.upper]-a[r.lower])*1e-6*(r.T-20)*.025**2/(4*.0004));if(r.upper===r.lower)near(r.delta,0);}result.numbers.push({mode,values});}assert.deepEqual(result.numbers[0].values,result.numbers[1].values);
result.devices=await p.evaluate(()=>{const cases=[];for(const scene of ['kettle','blanket'])for(const [upper,lower]of [['cu','iron'],['brass','cu']]){configure(lab,{scene,upper,lower});for(let i=0;i<1900&&!sim.ended;i++)lab.cfg.step(1/60,lab);cases.push({scene,upper,lower,T:sim.T,B:sim.B,t:sim.t,latched:sim.latched,boiling:sim.boiling,events:sim.events.map(x=>({...x})),max:sim.maxT});}const fine=[];for(const dt of [.05,.025]){configure(lab,{scene:'kettle',upper:'cu',lower:'iron'});while(!sim.ended)tick(lab.state,dt);fine.push({T:sim.T,B:sim.B,off:sim.events[0].t});}configure(lab,{scene:'kettle',upper:'cu',lower:'iron'});tick(lab.state);return {cases,fine,first:{T:sim.T,B:sim.B},reference:deflect({upper:'cu',lower:'iron'},90)};});
near(result.devices.first.T,20+1500*.05/4187);near(result.devices.first.B,20);near(result.devices.reference,.0004921875);const [k,bad,blanket]=result.devices.cases;assert.equal(k.latched,true);assert.equal(k.events.length,1);assert.equal(k.events[0].closed,false);assert.ok(k.max<100);assert.equal(bad.boiling,true);assert.equal(bad.T,100);assert.ok(blanket.events.length>=6);for(let i=1;i<blanket.events.length;i++)assert.notEqual(blanket.events[i].closed,blanket.events[i-1].closed);for(const key of ['T','B','off'])near(result.devices.fine[0][key],result.devices.fine[1][key],.1);
await p.evaluate(()=>localStorage.clear());await p.goto(url+'?mode=learn');
async function click(sel,t){const e=await p.evaluateHandle((s,t)=>[...document.querySelectorAll(s)].find(e=>e.textContent.trim()===t),sel,t);assert.ok(e.asElement(),t);await e.asElement().click();}
async function card(i,enter=false){await p.click(`.mcard:nth-child(${i+1}) .t`);if(enter)await p.click('.mcard.on .enter-btn');}
async function rec(){await click('.abtn','관찰 측정·기록');}
async function slider(T){await p.focus('input[aria-label="바이메탈 온도"]');await p.keyboard.press('Home');for(let i=-20;i<T;i+=10)await p.keyboard.press('ArrowRight');}
async function done(i){assert.equal(await p.evaluate(i=>!!lab.done[i],i),true);result.missions.push(i+1);}
await slider(80);await rec();await slider(0);await rec();await done(0);
await card(1,true);await p.click('.pbtn.main');await p.waitForFunction(()=>!lab.running&&sim.ended,{timeout:45000});await rec();await click('summary','더 해 보기 · 기기와 접점');await click('.seg button','직접 가열');await click('.seg button','켜지는 접점');await slider(120);await rec();await done(1);
await card(2,true);await rec();assert.equal(await p.evaluate(()=>!!lab.done[2]),false);await p.click('.mcard.on .pred button:nth-child(1)');await slider(0);await rec();await done(2);
await card(3,true);await p.select('.mcard.on select[aria-label="바꿀 것"]','target');await p.select('.mcard.on select[aria-label="잴 것"]','closed');for(const k of ['upper','lower','contact','side','heater','scene'])await p.click(`.mcard.on input[value="${k}"]`);await click('.mcard.on .abtn','이 설계로 실험하기');await rec();await rec();assert.equal(await p.evaluate(()=>!!lab.done[3]),false);await slider(120);await rec();await done(3);
await card(4,true);await click('.seg button','아래에서');await rec();await click('.seg button','위에서');await rec();await click('.seg[aria-label="아래 금속"] button','구리');await rec();await done(4);
await card(5);for(const b of await p.$$('.mcard.on .blank'))await(await b.$$('button'))[0].click();await done(5);
for(const [i,a]of [0,1,2].entries()){await p.click(`.quiz-question:nth-of-type(${i+1}) .quiz-options button:nth-child(${a+1})`);assert.match(await p.$eval(`.quiz-question:nth-of-type(${i+1}) .quiz-feedback`,e=>e.textContent),/맞았습니다/);}
for(const [w,h]of [[1920,1080],[1366,768],[1024,768],[390,844]])for(const mode of ['model','learn'])for(const scene of ['hot','cold','kettle','blanket']){await p.setViewport({width:w,height:h});await p.goto(url+'?mode='+mode);await p.evaluate(scene=>{configure(lab,{scene:['hot','cold'].includes(scene)?'manual':scene,upper:'cu',lower:'iron',target:scene==='hot'?120:0,contact:scene==='hot'?'on':'off',side:'down'});if(lab.state.scene!=='manual')for(let i=0;i<1900&&!sim.ended;i++)lab.cfg.step(1/60,lab);lab.update();},scene);await new Promise(r=>setTimeout(r,150));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const name=`bimetal-switch-${mode}-${scene}-${w}x${h}.png`;await p.screenshot({path:path.join(out,name)});result.screenshots.push(name);}assert.deepEqual(result.errors,[]);console.log('PASS bimetal: 160 analytic cases, device bounds/latch/cycling/convergence, 6 missions, 3 quizzes, 32 screens');
})().catch(e=>{result.failure=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify(result,null,2));if(browser)await browser.close();});

