const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),pp=require(process.env.PUPPETEER_PATH||'puppeteer-core');
const out=process.env.TEST_OUTPUT||path.resolve('test-results/buoyancy');fs.mkdirSync(out,{recursive:true});const result={numbers:[],missions:[],screenshots:[],errors:[]};let browser;const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
(async()=>{browser=await pp.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const p=await browser.newPage();p.on('pageerror',e=>result.errors.push(e.message));p.on('console',m=>{if(m.type()==='error')result.errors.push(m.text());});const url='http://127.0.0.1:7101/labs/buoyancy/';await p.setViewport({width:1920,height:1080});
 for(const mode of ['model','learn']){await p.goto(url+'?mode='+mode);const values=await p.evaluate(()=>Array.from({length:221},(_,raise)=>({raise,...physics(raise)})));for(const v of values){near(v.T+v.B+v.N,1.96);near(v.surface,360-v.raise-v.volume/40*8);assert.ok(v.T>=0&&v.N>=0);if(v.raise>0)assert.ok(v.B>=values[v.raise-1].B-1e-9);}near(values[0].T,1.96);near(values[80].T,1.8522);near(values[140].T,1.7444);near(values[180].B,.2156);near(values[220].T,0);near(values[220].N,1.7444);near(values[80].center,300);near(values[140].center,270);result.numbers.push({mode,values});}assert.deepEqual(result.numbers[0].values,result.numbers[1].values);
 await p.evaluate(()=>localStorage.clear());await p.goto(url+'?mode=learn');
 async function click(sel,t){const e=await p.evaluateHandle((sel,t)=>[...document.querySelectorAll(sel)].find(e=>e.textContent.trim()===t),sel,t);assert.ok(e.asElement(),t);await e.asElement().click();}
 async function height(x){await p.focus('input[aria-label="컵을 올린 높이"]');await p.keyboard.press('Home');for(let i=0;i<x;i+=10)await p.keyboard.press('ArrowRight');}
 async function card(i,enter=false){await p.click(`.mcard:nth-child(${i+1}) .t`);if(enter)await p.click('.mcard.on .enter-btn');}
 async function rec(){await click('.abtn','힘 센서 측정·기록');}
 async function done(i){assert.equal(await p.evaluate(i=>!!lab.done[i],i),true);result.missions.push(i+1);}
 await height(140);await done(0);await rec();assert.equal(await p.evaluate(()=>book.rows.length),0);
 await card(1,true);for(const x of [0,80,140]){await height(x);await rec();}await done(1);
 await card(2,true);const n=await p.evaluate(()=>book.rows.length);await rec();assert.equal(await p.evaluate(()=>book.rows.length),n);await p.click('.mcard.on .pred button:nth-child(2)');for(const x of [140,180]){await height(x);await rec();}await done(2);
 await card(3,true);await rec();await height(220);await rec();await done(3);
 await card(4);await p.select('.mcard.on select[aria-label="바꿀 것"]','immersion');await p.select('.mcard.on select[aria-label="잴 것"]','sensor');for(const k of ['count','water'])await p.click(`.mcard.on input[value="${k}"]`);await click('.mcard.on .abtn','이 설계로 실험하기');const before=await p.evaluate(()=>book.rows.length);await rec();assert.equal(await p.evaluate(()=>book.rows.length),before);await height(80);await rec();await rec();assert.equal(await p.evaluate(()=>!!lab.done[4]),false);await height(140);await rec();await done(4);
 await card(5);for(const b of await p.$$('.mcard.on .blank'))await(await b.$$('button'))[0].click();await done(5);
 for(const [i,a]of [0,1,2].entries()){await p.click(`.quiz-question:nth-of-type(${i+1}) .quiz-options button:nth-child(${a+1})`);assert.match(await p.$eval(`.quiz-question:nth-of-type(${i+1}) .quiz-feedback`,e=>e.textContent),/맞았습니다/);}
 const extremes=await p.evaluate(()=>{const orig=Math.random;let n=0;const failures=[];lab.mi=0;try{for(const e of [0,1]){Math.random=()=>e;lab.state.raise=0;const btn=[...document.querySelectorAll('.abtn')].find(e=>e.textContent==='힘 센서 측정·기록');btn.click();for(let raise=0;raise<=220;raise+=10){lab.state.raise=raise;const old=book.rows.length;btn.click();n++;if(book.rows.length!==old+1)failures.push(raise);}}}finally{Math.random=orig;}return{n,failures};});assert.deepEqual(extremes.failures,[]);result.measurementEndpoints=extremes.n;
 for(const [w,h]of [[1920,1080],[1366,768],[1024,768],[390,844]])for(const mode of ['model','learn'])for(const raise of [80,140,220]){await p.setViewport({width:w,height:h});await p.goto(url+'?mode='+mode);await p.evaluate(raise=>{lab.state.raise=raise;lab.update();},raise);await new Promise(r=>setTimeout(r,120));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const name=`buoyancy-${mode}-${raise}-${w}x${h}.png`;await p.screenshot({path:path.join(out,name)});result.screenshots.push(name);}
 assert.deepEqual(result.errors,[]);console.log('PASS buoyancy: 442 numeric cases, 6 missions, 3 quizzes, 46 measurement endpoints, 24 screens');
})().catch(e=>{result.failure=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify(result,null,2));if(browser)await browser.close();});
