const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),pp=require(process.env.PUPPETEER_PATH||'puppeteer-core');const out=process.env.TEST_OUTPUT||path.resolve('test-results/conduction-camera');fs.mkdirSync(out,{recursive:true});const result={numbers:[],missions:[],screenshots:[],errors:[]};let browser;const near=(a,b,eps=1e-7)=>assert.ok(Math.abs(a-b)<eps,`${a} != ${b}`);
(async()=>{browser=await pp.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const p=await browser.newPage();p.on('pageerror',e=>result.errors.push(e.message));p.on('console',m=>{if(m.type()==='error')result.errors.push(m.text());});const url='http://127.0.0.1:7101/labs/conduction-camera/';await p.setViewport({width:1920,height:1080});
 for(const mode of ['model','learn']){await p.goto(url+'?mode='+mode);await p.waitForFunction(()=>window.lab);const values=await p.evaluate(()=>Object.keys(MAT).flatMap(material=>['block','dip'].map(device=>{const p=makePlate(material,device),initial=p.initial;stepPlate(p,device);const first=p.a[center],blockFirst=p.block;for(let i=1;i<6000;i++)stepPlate(p,device);return {material,device,initial,energy:energy(p),first,blockFirst,center:p.a[center],probe:p.a[probe],min:Math.min(...p.a),max:Math.max(...p.a),block:p.block,skin:skin(material),maskCount:mask.filter(Boolean).length};})));for(const r of values){near(r.energy,r.initial,1e-6);assert.ok(r.min>=20-1e-8&&r.max<=70+1e-8);if(r.material==='al'&&r.device==='block'){const cv=2.43e6,alpha=9.7e-5,hc=1/(1/500+.002/(alpha*cv)),area=(.1/28)**2;near(r.first,20+hc*50*.01/(cv*.002));near(r.blockFirst,70-r.maskCount*hc*area*50*.01/38);}if(r.device==='block')assert.ok(r.block<70);}const a=values.find(r=>r.material==='al'&&r.device==='block'),plastic=values.find(r=>r.material==='plastic'&&r.device==='block');assert.ok(a.probe>plastic.probe+1);assert.ok(plastic.center>20);assert.ok(a.skin<values.find(r=>r.material==='wood').skin);result.numbers.push({mode,values});}assert.deepEqual(result.numbers[0].values,result.numbers[1].values);
 await p.evaluate(()=>localStorage.clear());await p.goto(url+'?mode=learn');
 async function click(sel,t){const e=await p.evaluateHandle((sel,t)=>[...document.querySelectorAll(sel)].find(e=>e.textContent.trim()===t),sel,t);assert.ok(e.asElement(),t);await e.asElement().click();}
 async function card(i,enter=false){await p.click(`.mcard:nth-child(${i+1}) .t`);if(enter)await p.click('.mcard.on .enter-btn');}
 async function minute(){const start=await p.evaluate(()=>sim.t);await p.click('.pbtn.main');await p.waitForFunction(start=>!lab.running&&sim.t>=start+60-1e-6,{timeout:15000},start);}
 async function rec(){await click('.abtn','두 판 측정·기록');}
 async function done(i){assert.equal(await p.evaluate(i=>!!lab.done[i],i),true);result.missions.push(i+1);}
 await minute();await done(0);await card(1,true);await rec();await minute();await rec();await done(1);
 await card(2,true);const n=await p.evaluate(()=>book.rows.length);await rec();assert.equal(await p.evaluate(()=>book.rows.length),n);await p.click('.mcard.on .pred button:nth-child(2)');await rec();await done(2);
 await card(3,true);for(let i=0;i<3;i++){await minute();await rec();}await done(3);
 await card(4);await p.select('.mcard.on select[aria-label="바꿀 것"]','left');await p.select('.mcard.on select[aria-label="잴 것"]','leftProbe');for(const k of ['right','device','time'])await p.click(`.mcard.on input[value="${k}"]`);await click('.mcard.on .abtn','이 설계로 실험하기');await click('.pbtn','↺ 처음부터');await minute();await rec();await rec();assert.equal(await p.evaluate(()=>!!lab.done[4]),false);const left=await p.$$('.seg');await(await left[1].$$('button'))[0].click();await minute();await rec();await done(4);
 await card(5);for(const b of await p.$$('.mcard.on .blank'))await(await b.$$('button'))[0].click();await done(5);
 for(const [i,a]of [0,1,2].entries()){await p.click(`.quiz-question:nth-of-type(${i+1}) .quiz-options button:nth-child(${a+1})`);assert.match(await p.$eval(`.quiz-question:nth-of-type(${i+1}) .quiz-feedback`,e=>e.textContent),/맞았습니다/);}
 for(const [w,h]of [[1920,1080],[1366,768],[1024,768],[390,844]])for(const mode of ['model','learn'])for(const device of ['block','dip','hand']){await p.setViewport({width:w,height:h});await p.goto(url+'?mode='+mode);await p.evaluate(device=>{configure(lab,{device,left:device==='dip'?'cu':'al',right:device==='hand'?'wood':'plastic'});if(device!=='hand'){for(let i=0;i<6000;i++)for(const p of sim.plates)stepPlate(p,device);sim.t=60;}lab.update();},device);await new Promise(r=>setTimeout(r,150));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const name=`conduction-camera-${mode}-${device}-${w}x${h}.png`;await p.screenshot({path:path.join(out,name)});result.screenshots.push(name);}
 assert.deepEqual(result.errors,[]);console.log('PASS conduction camera: 24 numeric cases, 6 missions, 3 quizzes, 24 screens');
})().catch(e=>{result.failure=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify(result,null,2));if(browser)await browser.close();});
