const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),pp=require(process.env.PUPPETEER_PATH||'puppeteer-core');
const out=process.env.TEST_OUTPUT||'test-results/equilibrium-motion';fs.mkdirSync(out,{recursive:true});let browser;const report={};
const near=(a,b,eps=1e-8)=>assert.ok(Math.abs(a-b)<eps,`${a} != ${b}`);
(async()=>{browser=await pp.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const p=await browser.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:7101/labs/heat-equilibrium/?mode=model');await p.waitForFunction(()=>window.lab);
 report.motion=await p.evaluate(()=>{
  const stat=()=>particles.map(ps=>({rms:Math.sqrt(ps.reduce((s,p)=>s+p.vx*p.vx+p.vy*p.vy,0)/ps.length),mean:ps.reduce((s,p)=>s+Math.hypot(p.vx,p.vy),0)/ps.length,count:ps.length}));
  const rows=[];for(const ts of [[60,5],[5,60],[33.36,33.36]]){initParticles();moveParticles(1/240,ts);const before=stat(),distance=[0,0];for(let i=0;i<480;i++){const ss=stat();for(let k=0;k<2;k++)distance[k]+=ss[k].mean/240;moveParticles(1/240,ts);}rows.push({ts,before,after:stat(),distance,trailLength:particles[0][0].trail.length});}
  function run(fps){initParticles();for(let i=0;i<fps*2;i++)moveParticles(1/fps,[60,5]);return particles.flatMap(ps=>ps.flatMap(p=>[p.x,p.y,p.vx,p.vy]));}
  const run60=run(60);return {rows,frameDifference:Math.max(...run(30).map((v,i)=>Math.abs(v-run60[i])))};
 });
 for(const row of report.motion.rows){for(let i=0;i<2;i++){near(row.before[i].rms,90*Math.sqrt((row.ts[i]+273.15)/293.15));near(row.after[i].rms,row.before[i].rms);assert.equal(row.after[i].count,48);}assert.equal(row.trailLength,10);}
 assert.ok(report.motion.rows[0].distance[0]>report.motion.rows[0].distance[1]);assert.ok(report.motion.rows[1].distance[1]>report.motion.rows[1].distance[0]);near(report.motion.frameDifference,0);
 report.equilibrium=await p.evaluate(()=>{const initial=temperatures({inside:60,outside:5,contact:'together'},0),end=temperatures({inside:60,outside:5,contact:'together'},600);return {initial:initial.map(rms),end:end.map(rms)};});assert.ok(report.equilibrium.end[0]<report.equilibrium.initial[0]);assert.ok(report.equilibrium.end[1]>report.equilibrium.initial[1]);assert.ok(Math.abs(report.equilibrium.end[0]/report.equilibrium.end[1]-1)<.001);
 // Rendered motion must advance even when the macroscopic experiment is paused.
 const before=await p.evaluate(()=>({x:particles[0][0].x,y:particles[0][0].y,t:sim.t}));await new Promise(r=>setTimeout(r,250));const after=await p.evaluate(()=>({x:particles[0][0].x,y:particles[0][0].y,t:sim.t}));assert.equal(after.t,before.t);assert.ok(Math.hypot(after.x-before.x,after.y-before.y)>1);report.pausedMotion={before,after};
 await p.click('[data-view="scene"]');await p.evaluate(()=>[...document.querySelectorAll('.seg button')].find(e=>e.textContent==='입자 크게').click());assert.equal(await p.evaluate(()=>lab.modelVisible&&lab.state.focus==='particles'),true);
 await p.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);await new Promise(r=>setTimeout(r,100));const frozen=await p.evaluate(()=>particles.map(ps=>ps.map(p=>[p.x,p.y])));await new Promise(r=>setTimeout(r,150));assert.deepEqual(await p.evaluate(()=>particles.map(ps=>ps.map(p=>[p.x,p.y]))),frozen);report.reducedMotion=true;
 report.layout=await p.evaluate(()=>{
  const cv=document.createElement('canvas');cv.width=960;cv.height=600;const c=cv.getContext('2d'),original=c.fillText.bind(c),oldfs=lab.fs;let labels=[];c.fillText=(t,x,y)=>{const m=c.measureText(t);labels.push({text:t,x:x-m.actualBoundingBoxLeft,y:y-m.actualBoundingBoxAscent,w:m.actualBoundingBoxLeft+m.actualBoundingBoxRight,h:m.actualBoundingBoxAscent+m.actualBoundingBoxDescent});original(t,x,y);};lab.fs=x=>Math.max(30,x);const bad=[],clipped=[];let cases=0;
  for(const contact of ['apart','together'])for(const view of ['all','particles','scene'])for(const inside of [5,80]){configure(lab,{contact,inside,outside:85-inside,focus:view==='particles'?'particles':'all'});lab.modelVisible=view!=='scene';labels=[];lab.cfg.draw(c,lab);cases++;for(const a of labels)if(a.x<0||a.x+a.w>960||a.y<0||a.y+a.h>600)clipped.push({contact,view,text:a.text,box:a});for(let i=0;i<labels.length;i++)for(let j=i+1;j<labels.length;j++){const a=labels[i],b=labels[j],dx=Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x),dy=Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y);if(dx>3&&dy>3)bad.push({contact,view,a:a.text,b:b.text,dx,dy});}}
  lab.fs=oldfs;return{cases,bad,clipped};
 });assert.deepEqual(report.layout.bad,[]);assert.deepEqual(report.layout.clipped,[]);assert.deepEqual(errors,[]);console.log('PASS equilibrium motion: RMS scaling, measured paths, frame independence, paused/reduced motion, focus switching and 12 layouts');
})().catch(e=>{report.failure=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(out,'motion-validation.json'),JSON.stringify(report,null,2));if(browser)await browser.close();});
