const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),pp=require(process.env.PUPPETEER_PATH||'puppeteer-core');
const base=process.env.LAB_URL||'http://127.0.0.1:7101',out=process.env.TEST_OUTPUT||'test-results/grade-catalog';fs.mkdirSync(out,{recursive:true});let b;const report={errors:[],screens:[]};
(async()=>{b=await pp.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const p=await b.newPage();p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=400)report.errors.push(r.status()+' '+r.url());});
 await p.goto(base+'/',{waitUntil:'networkidle0'});
 const data=await p.evaluate(()=>({groups:[...document.querySelectorAll('.grade-section')].map(e=>({grade:+e.dataset.grade,count:e.querySelectorAll('.card').length,units:[...e.querySelectorAll('.unit-section')].map(x=>+x.dataset.order)})),ids:[...document.querySelectorAll('#grid .card')].map(e=>e.dataset.id),unmapped:SIMS.filter(s=>s.own&&!placement(s).grade).map(s=>s.id),units:CurriculumOrder.units}));
 assert.equal(data.ids.length,134);assert.equal(new Set(data.ids).size,134);assert.deepEqual(data.groups.map(x=>x.grade),[1,2,3,0]);assert.deepEqual(data.unmapped,[]);for(const g of data.groups)assert.deepEqual(g.units,[...g.units].sort((a,b)=>a-b));
 const source=JSON.parse(fs.readFileSync(path.join(__dirname,'../curriculum/units.json'),'utf8'));assert.deepEqual(data.units.map(u=>[u.id,u.title]),source.map(u=>[u.id,u.title]));report.groups=data.groups;
 assert.equal(await p.$$eval('.mode-actions',es=>es.length),63);
 for(const g of ['1','2','3','0']){await p.click(`#gradeRow [data-g="${g}"]`);assert.deepEqual(await p.$$eval('.grade-section',es=>es.map(e=>e.dataset.grade)),[g]);assert.ok(p.url().includes('grade='+g));await p.reload();assert.equal(await p.$eval(`#gradeRow [data-g="${g}"]`,e=>e.getAttribute('aria-pressed')),'true');}
 await p.click('#gradeRow [data-g="2"]');await p.click('#subjRow [data-s="phys"]');assert.ok(await p.$$eval('#grid .card',es=>es.length)>0);assert.ok(await p.evaluate(()=>[...document.querySelectorAll('#grid .card')].every(e=>SIMS.find(s=>s.id===e.dataset.id).subject==='phys')));
 await p.type('#q','도저히없는검색어');assert.equal(await p.$$eval('#grid .card',es=>es.length),0);
 await p.click('#inquiryPath summary');await p.click('[data-unit="m13-08"]');assert.equal(await p.$eval('#q',e=>e.value),'');assert.ok(await p.$('#catalog-m13-08'));assert.ok(await p.$$eval('#grid .card',es=>es.length)>0);
 await p.evaluate(()=>localStorage.setItem('cs-lab-density-lab-v1',JSON.stringify([true,false,true,false])));await p.reload();assert.match(await p.$eval('[data-id="density-lab"] .progress-dots',e=>e.textContent),/2\/4/);
 await p.goto(base+'/curriculum/',{waitUntil:'networkidle0'});await p.waitForSelector('.school-grade');assert.deepEqual(await p.$$eval('.school-grade',es=>es.map(e=>({g:e.dataset.grade,n:e.querySelectorAll('.unit').length}))),[{g:'1',n:7},{g:'2',n:8},{g:'3',n:8}]);
 await p.select('#grade','3');assert.equal(await p.$$eval('.unit',es=>es.length),8);assert.equal(await p.$$eval('#nav a',es=>es.length),8);await p.reload();await p.waitForSelector('.unit');assert.equal(await p.$eval('#grade',e=>e.value),'3');
 for(const [w,h]of [[1920,1080],[1366,768],[1024,768],[390,844]])for(const route of ['/?grade=2','/curriculum/?grade=3']){await p.setViewport({width:w,height:h});await p.goto(base+route,{waitUntil:'networkidle0'});await p.waitForSelector('.card');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const name=`${route.startsWith('/?')?'gallery':'map'}-${w}x${h}.png`;await p.screenshot({path:path.join(out,name)});report.screens.push(name);if(route.startsWith('/?')){await p.$eval('.grade-section',e=>e.scrollIntoView());await p.screenshot({path:path.join(out,'cards-'+w+'x'+h+'.png')});}}
 assert.deepEqual(report.errors,[]);console.log('PASS grade categories: 134 unique cards, 63 dual-mode links, grade/unit order, filters, URLs, progress and four viewports');
})().catch(e=>{report.failure=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify(report,null,2));if(b)await b.close();});
