const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),pp=require(process.env.PUPPETEER_PATH||'puppeteer-core');const out=process.env.TEST_OUTPUT||path.resolve('test-results/motion');fs.mkdirSync(out,{recursive:true});const result={numbers:[],missions:[],screenshots:[],errors:[]};let browser;const near=(a,b,eps=1e-7)=>assert.ok(Math.abs(a-b)<eps,`${a} != ${b}`);
(async()=>{browser=await pp.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const p=await browser.newPage();p.on('pageerror',e=>result.errors.push(e.message));p.on('console',m=>{if(m.type()==='error')result.errors.push(m.text());});const url='http://127.0.0.1:7101/labs/motion/';await p.setViewport({width:1920,height:1080});
 for(const mode of ['model','learn']){await p.goto(url+'?mode='+mode);await p.waitForFunction(()=>window.lab);const values=await p.evaluate(()=>Object.keys(CASES).map(k=>{choose(lab,k);lab.cfg.onPlay(lab);for(let i=0;i<800&&!sim.ended;i++)lab.cfg.step(1/60,lab);return {case:k,end:at(k,sim.t),t:sim.t,maxDv:sim.maxDv,maxAngle:sim.maxAngle,type:classification(sim,k),cutDv:sim.cutDv,cutAngle:sim.cutAngle};}));const r=Object.fromEntries(values.map(r=>[r.case,r]));near(r.none.end.x,1.2);near(r.none.end.speed,.6);near(r.back.end.x,1.6);near(r.back.end.speed,1);near(r.front.end.x,.8);near(r.front.end.speed,.2);near(r.side.end.y,.4);near(r.side.end.speed,Math.sqrt(.52));near(r.circle.end.x,0);near(r.circle.end.speed,.6);near(r.cut.cutDv,0);near(r.cut.cutAngle,0,1e-5);near(r.throw.end.speed,Math.hypot(1.2,2.4));near(r.throw.maxDv,Math.hypot(1.2,2.4)-1.2,.001);for(const [k,type]of Object.entries({still:0,none:0,back:1,front:1,side:3,circle:2,cut:2,throw:3}))assert.equal(r[k].type,type,k);result.numbers.push({mode,values});}assert.deepEqual(result.numbers[0].values,result.numbers[1].values);
 await p.evaluate(()=>localStorage.clear());await p.goto(url+'?mode=learn');
 async function click(sel,t){const e=await p.evaluateHandle((sel,t)=>[...document.querySelectorAll(sel)].find(e=>e.textContent.trim()===t),sel,t);assert.ok(e.asElement(),t);await e.asElement().click();}
 async function card(i,enter=false){await p.click(`.mcard:nth-child(${i+1}) .t`);if(enter)await p.click('.mcard.on .enter-btn');}
 async function run(k){const name=await p.evaluate(k=>CASES[k],k);await click('.seg button',name);await click('.speed button','보통');await p.click('.pbtn.main');await p.waitForFunction(()=>sim.ended,{timeout:10000});}
 async function rec(){await click('.abtn','운동 측정·기록');}
 async function done(i){assert.equal(await p.evaluate(i=>!!lab.done[i],i),true);result.missions.push(i+1);}
 await rec();assert.equal(await p.evaluate(()=>book.rows.length),0);for(const k of ['none','back','side'])await run(k);await done(0);
 await card(1,true);for(const k of ['back','front','side']){await run(k);await rec();}await done(1);
 await card(2,true);assert.equal(await p.$eval('.pbtn.main',e=>e.disabled),true);await p.click('.mcard.on .pred button:nth-child(1)');await run('none');await rec();await done(2);
 await card(3,true);for(const k of ['circle','cut']){await run(k);await rec();}await done(3);
 await card(4);await p.select('.mcard.on select[aria-label="바꿀 것"]','case');await p.select('.mcard.on select[aria-label="잴 것"]','maxDv');for(const k of ['mass','initial'])await p.click(`.mcard.on input[value="${k}"]`);await click('.mcard.on .abtn','이 설계로 실험하기');await run('front');await rec();await rec();assert.equal(await p.evaluate(()=>!!lab.done[4]),false);await run('side');await rec();await done(4);
 await card(5);await click('.abtn','여덟 사례 한꺼번에 채점');assert.equal(await p.evaluate(()=>!!lab.done[5]),false);const correct={still:0,none:0,back:1,front:1,side:3,circle:2,cut:2,throw:3};for(const [k,type]of Object.entries(correct)){await run(k);await p.select(`[data-classify="${k}"]`,String(type));assert.equal(await p.evaluate(()=>!!lab.done[5]),false);}await p.select('[data-classify="throw"]','2');await click('.abtn','여덟 사례 한꺼번에 채점');assert.equal(await p.evaluate(()=>!!lab.done[5]),false);await p.select('[data-classify="throw"]','3');await click('.abtn','여덟 사례 한꺼번에 채점');await done(5);
 await card(6,true);for(const b of await p.$$('.mcard.on .blank'))await(await b.$$('button'))[0].click();await done(6);
 for(const [i,a]of [0,1,2].entries()){await p.click(`.quiz-question:nth-of-type(${i+1}) .quiz-options button:nth-child(${a+1})`);assert.match(await p.$eval(`.quiz-question:nth-of-type(${i+1}) .quiz-feedback`,e=>e.textContent),/맞았습니다/);}
 for(const [w,h]of [[1920,1080],[1366,768],[1024,768],[390,844]])for(const mode of ['model','learn'])for(const k of ['side','cut','throw']){await p.setViewport({width:w,height:h});await p.goto(url+'?mode='+mode);await p.evaluate(k=>{choose(lab,k);lab.cfg.onPlay(lab);for(let i=0;i<800&&!sim.ended;i++)lab.cfg.step(1/60,lab);lab.update();},k);await new Promise(r=>setTimeout(r,150));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const name=`motion-${mode}-${k}-${w}x${h}.png`;await p.screenshot({path:path.join(out,name)});result.screenshots.push(name);}
 assert.deepEqual(result.errors,[]);console.log('PASS motion: 16 numeric scenarios, 7 missions, 3 quizzes, 24 screens');
})().catch(e=>{result.failure=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify(result,null,2));if(browser)await browser.close();});
