const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),pp=require(process.env.PUPPETEER_PATH||'puppeteer-core');const out=process.env.TEST_OUTPUT||path.resolve('test-results/particle-motion');fs.mkdirSync(out,{recursive:true});const result={numbers:[],missions:[],screenshots:[],errors:[]};let browser;const near=(a,b,e=1e-8)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
(async()=>{browser=await pp.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const p=await browser.newPage();p.on('pageerror',e=>result.errors.push(e.message));p.on('console',m=>{if(m.type()==='error')result.errors.push(m.text());});const url='http://127.0.0.1:7101/labs/particle-motion/';await p.setViewport({width:1920,height:1080});
for(const mode of ['model','learn']){await p.goto(url+'?mode='+mode);await p.waitForFunction(()=>window.lab);const values=await p.evaluate(()=>{const out=[];for(const scene of ['ink','perfume']){configure(lab,{scene,source:'center',window:'closed',drops:1,sprays:4});load(lab);const energy=()=>sim.ps.reduce((n,p)=>n+(p.vx*p.vx+p.vy*p.vy)/2,0),initialEnergy=energy(),initialMean=sim.ps.filter(p=>p.kind==='solute').reduce((n,p)=>n+Math.hypot(p.x,p.y),0)/sim.initial;for(let i=0;i<450;i++)lab.cfg.step(1/60,lab);const at30={scene,t:sim.t,count:sim.ps.length,initial:sim.initial,remaining:sim.ps.filter(p=>p.kind==='solute').length,energyError:(energy()-initialEnergy)/initialEnergy,sensed:[...sim.sensed],initialMean,mean:sim.ps.filter(p=>p.kind==='solute').reduce((n,p)=>n+Math.hypot(p.x,p.y),0)/sim.initial,bounds:sim.ps.every(p=>scene==='ink'?Math.hypot(p.x,p.y)<=169.00001:p.x>=4&&p.x<=716&&p.y>=4&&p.y<=296),movingMedium:sim.ps.filter(p=>p.kind==='medium'&&Math.hypot(p.x-p.x0,p.y-p.y0)>10).length};if(scene==='perfume'){lab.state.window='open';for(let i=0;i<450;i++)lab.cfg.step(1/60,lab);at30.open={remaining:sim.ps.filter(p=>p.kind==='solute').length,escaped:sim.escaped};}out.push(at30);}for(const drops of [1,3,5]){configure(lab,{scene:'evap',evaporate:drops});load(lab);const counts0=counts(sim.transfer);for(let i=0;i<900;i++)lab.cfg.step(1/60,lab);out.push({scene:'evap',drops,t:sim.t,initial:counts0,counts:counts(sim.transfer),mass:mass()});}return out;});for(const r of values){if(r.scene==='evap'){assert.equal(r.counts.reduce((a,b)=>a+b),r.drops*8);near(r.mass,r.counts[0]*.015/8);assert.ok(r.mass<r.drops*.015);}else{assert.ok(Math.abs(r.energyError)<1e-10);assert.ok(r.bounds);assert.ok(r.movingMedium>100);assert.equal(r.initial,r.remaining);if(r.scene==='ink')assert.ok(r.mean>r.initialMean+10);else{assert.equal(r.sensed.filter(x=>x!=null).length,6);assert.ok(r.open.escaped>0);assert.equal(r.open.remaining+r.open.escaped,r.initial);}}}result.numbers.push({mode,values});}assert.deepEqual(result.numbers[0].values,result.numbers[1].values);
result.statistical=await p.evaluate(()=>{const avg=[0,0,0];for(let i=1;i<=2000;i++){const e=transfer(40,(i*2654435761)>>>0);advanceTransfer(e,60);counts(e).forEach((n,k)=>avg[k]+=n/2000);}const one=transfer(40,301),many=transfer(40,301);advanceTransfer(one,60);for(let i=1;i<=600;i++)advanceTransfer(many,i*.1);return {avg,one:counts(one),many:counts(many)};});const a=.035,b=.002,c=.08,D=Math.sqrt((a+b+c)**2-4*a*c),r1=(-(a+b+c)+D)/2,r2=(-(a+b+c)-D)/2,w=(-a-r2)/D,L=40*(w*Math.exp(r1*60)+(1-w)*Math.exp(r2*60)),G=40*a/D*(Math.exp(r1*60)-Math.exp(r2*60));[L,G,40-L-G].forEach((n,i)=>near(result.statistical.avg[i],n,.22));assert.deepEqual(result.statistical.one,result.statistical.many);
await p.evaluate(()=>localStorage.clear());await p.goto(url+'?mode=learn');
async function click(sel,t){const e=await p.evaluateHandle((s,t)=>[...document.querySelectorAll(s)].find(e=>e.textContent.trim()===t),sel,t);assert.ok(e.asElement(),t);await e.asElement().click();}
async function card(i,enter=false){await p.click(`.mcard:nth-child(${i+1}) .t`);if(enter)await p.click('.mcard.on .enter-btn');}
async function put(tare=false){if(tare)await click('.abtn','빈 접시 영점 맞추기');await click('.abtn','선택한 물질 넣기');}
async function until(t){await p.click('.pbtn.main');await p.waitForFunction(t=>sim.t>=t,{timeout:45000},t);if(await p.evaluate(()=>lab.running))await p.click('.pbtn.main');}
async function rec(){await click('.abtn','관찰 기록');}
async function done(i){assert.equal(await p.evaluate(i=>!!lab.done[i],i),true);result.missions.push(i+1);}
await put();await until(5);await rec();await click('.seg button','공기 중 향수');await put();await until(5);await rec();await click('.seg button','아세톤 증발');await put(true);await until(5);await rec();await done(0);
await card(1,true);await put();assert.equal(await p.$eval('.pbtn.main',e=>e.disabled),true);await p.click('.mcard.on .pred button:nth-child(3)');await until(10);await rec();await done(1);
await card(2,true);await put();await until(25);await rec();await click('.seg button','열림');await until(45);await rec();await done(2);
await card(3,true);await put(true);await until(60);await rec();await done(3);
await card(4,true);await p.select('.mcard.on select[aria-label="바꿀 것"]','seconds');await p.select('.mcard.on select[aria-label="잴 것"]','measured');for(const k of ['scene','dose','tare'])await p.click(`.mcard.on input[value="${k}"]`);await click('.mcard.on .abtn','이 설계로 실험하기');await put(true);await rec();await rec();assert.equal(await p.evaluate(()=>!!lab.done[4]),false);await until(10);await rec();await done(4);
await card(5);for(const b of await p.$$('.mcard.on .blank'))await(await b.$$('button'))[0].click();await done(5);
for(const [i,a]of [0,1,2].entries()){await p.click(`.quiz-question:nth-of-type(${i+1}) .quiz-options button:nth-child(${a+1})`);assert.match(await p.$eval(`.quiz-question:nth-of-type(${i+1}) .quiz-feedback`,e=>e.textContent),/맞았습니다/);}
for(const [w,h]of [[1920,1080],[1366,768],[1024,768],[390,844]])for(const mode of ['model','learn'])for(const scene of ['ink','perfume','evap']){await p.setViewport({width:w,height:h});await p.goto(url+'?mode='+mode);await p.evaluate(scene=>{configure(lab,{scene,window:'closed',source:'center',drops:1,sprays:4,evaporate:5});lab.state.tare=true;load(lab);for(let i=0;i<450;i++)lab.cfg.step(1/60,lab);lab.update();},scene);await new Promise(r=>setTimeout(r,150));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const name=`particle-motion-${mode}-${scene}-${w}x${h}.png`;await p.screenshot({path:path.join(out,name)});result.screenshots.push(name);}assert.deepEqual(result.errors,[]);console.log('PASS particles: elastic energy/counts, transfer ensemble and conservation, 6 missions, 3 quizzes, 24 screens');
})().catch(e=>{result.failure=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify(result,null,2));if(browser)await browser.close();});
