const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),pp=require(process.env.PUPPETEER_PATH||'puppeteer-core');const out=process.env.TEST_OUTPUT||path.resolve('test-results/specific-heat');fs.mkdirSync(out,{recursive:true});const result={numbers:[],missions:[],screenshots:[],errors:[]};let browser;const near=(a,b,eps=1e-7)=>assert.ok(Math.abs(a-b)<eps,`${a} != ${b}`);
(async()=>{browser=await pp.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const p=await browser.newPage();p.on('pageerror',e=>result.errors.push(e.message));p.on('console',m=>{if(m.type()==='error')result.errors.push(m.text());});const url='http://127.0.0.1:7101/labs/specific-heat/';await p.setViewport({width:1920,height:1080});
 for(const mode of ['model','learn']){await p.goto(url+'?mode='+mode);await p.waitForFunction(()=>window.lab);const values=await p.evaluate(()=>Object.keys(MAT).flatMap(key=>[25,50,100].flatMap(amount=>['heat','cool'].map(method=>{configure(lab,{left:key,right:'water',amount,method});lab.cfg.onPlay(lab);for(let i=0;i<1300&&!sim.ended;i++)lab.cfg.step(1/60,lab);return {key,ratio:MAT[key].ratio,amount,method,t:sim.t,limit:duration(lab.state),T:temperature(key,amount,method,sim.t),water:temperature('water',amount,method,sim.t),time40:crossing(key,amount,40)};}))));for(const r of values){near(r.t,r.limit);const C=r.ratio*4187*r.amount/1000,expected=r.method==='heat'?20+20/.15*(1-Math.exp(-.15*r.t/C)):20+40*Math.exp(-.15*r.t/C);near(r.T,expected);near(r.time40,-C/.15*Math.log(.85));assert.ok(r.T<=(r.key==='ethanol'&&r.method==='heat'?70:80)+1e-7);}result.numbers.push({mode,values});}assert.deepEqual(result.numbers[0].values,result.numbers[1].values);
 await p.evaluate(()=>localStorage.clear());await p.goto(url+'?mode=learn');
 async function click(sel,t){const e=await p.evaluateHandle((sel,t)=>[...document.querySelectorAll(sel)].find(e=>e.textContent.trim()===t),sel,t);assert.ok(e.asElement(),t);await e.asElement().click();}
 async function card(i,enter=false){await p.click(`.mcard:nth-child(${i+1}) .t`);if(enter)await p.click('.mcard.on .enter-btn');}
 async function minute(){const start=await p.evaluate(()=>sim.t);await p.click('.pbtn.main');await p.waitForFunction(start=>!lab.running&&(sim.t>=start+60-1e-6||sim.ended),{timeout:15000},start);}
 async function rec(){await click('.abtn','두 시료 측정·기록');}
 async function done(i){assert.equal(await p.evaluate(i=>!!lab.done[i],i),true);result.missions.push(i+1);}
 async function pair(a,b){const names=await p.evaluate(([a,b])=>[MAT[a].name,MAT[b].name],[a,b]);for(const [index,name]of names.entries()){const groups=await p.$$('.seg');const buttons=await groups[index+1].$$('button');for(const button of buttons)if(await button.evaluate(e=>e.textContent)===name){await button.click();break;}}}
 await minute();await rec();await click('.seg button','냉각');await minute();await rec();await done(0);
 await card(1,true);for(let i=0;i<5;i++)await minute();await rec();await click('.seg button','냉각');await minute();await rec();await done(1);
 await card(2,true);assert.equal(await p.$eval('.pbtn.main',e=>e.disabled),true);await p.click('.mcard.on .pred button:nth-child(2)');await minute();await rec();await done(2);
 await card(3,true);await p.select('.mcard.on select[aria-label="바꿀 것"]','left');await p.select('.mcard.on select[aria-label="잴 것"]','measuredLeft');for(const k of ['right','amount','method','seconds'])await p.click(`.mcard.on input[value="${k}"]`);await click('.mcard.on .abtn','이 설계로 실험하기');await minute();await rec();await rec();assert.equal(await p.evaluate(()=>!!lab.done[3]),false);await pair('al','oil');await minute();await rec();await done(3);
 await card(4,true);await click('.abtn','비열 순서 한꺼번에 채점');assert.equal(await p.evaluate(()=>!!lab.done[4]),false);for(const [a,b,n]of [['water','oil',4],['sand','al',1],['iron','ethanol',1],['ethanol','water',3]]){await pair(a,b);for(let i=0;i<n;i++)await minute();await rec();}for(const [i,k]of ['iron','sand','al','oil','ethanol','water'].entries())await p.select(`[data-rank="${i}"]`,k);assert.equal(await p.evaluate(()=>!!lab.done[4]),false);await click('.abtn','비열 순서 한꺼번에 채점');await done(4);
 await card(5);for(const b of await p.$$('.mcard.on .blank'))await(await b.$$('button'))[0].click();await done(5);
 for(const [i,a]of [1,0,2].entries()){await p.click(`.quiz-question:nth-of-type(${i+1}) .quiz-options button:nth-child(${a+1})`);assert.match(await p.$eval(`.quiz-question:nth-of-type(${i+1}) .quiz-feedback`,e=>e.textContent),/맞았습니다/);}
 for(const [w,h]of [[1920,1080],[1366,768],[1024,768],[390,844]])for(const mode of ['model','learn'])for(const scene of ['heat','cool','solid']){await p.setViewport({width:w,height:h});await p.goto(url+'?mode='+mode);await p.evaluate(scene=>{configure(lab,{method:scene==='cool'?'cool':'heat',left:scene==='solid'?'al':'water',right:scene==='solid'?'water':'oil',amount:50});for(let i=0;i<1300&&!sim.ended;i++)lab.cfg.step(1/60,lab);lab.update();},scene);await new Promise(r=>setTimeout(r,150));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const name=`specific-heat-${mode}-${scene}-${w}x${h}.png`;await p.screenshot({path:path.join(out,name)});result.screenshots.push(name);}
 assert.deepEqual(result.errors,[]);console.log('PASS specific heat: 72 numeric cases, 6 missions, 3 quizzes, 24 screens');
})().catch(e=>{result.failure=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify(result,null,2));if(browser)await browser.close();});

